#####################################################################
#																	 
#	Created by u'nSP IDE		13:31:33	10/01/09
#
#####################################################################




APPDIR	= C:\PROGRA~1\Sunplus\UNSPID~1.0

OUTDIR	= .\Debug

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"F:/myproject/lingyang/sound"

BODY	= -body SPCE060A_061A -bfile "C:\Program Files\Sunplus\unSP IDE Common\Body\SPCE060A_061A.cpt"

BINFILE	= "$(OUTDIR)\sound.S37"

ARYFILE	= "$(OUTDIR)\sound.ary"

SBMFILE	= "$(OUTDIR)\sound.sbm"

OPT	= -S -gstabs -Wall -mglobal-var-iram

ASFLAGS	= -t2 -d

CASFLAGS	= -t2 

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	= 

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\0_16k.res" \
	"$(OUTDIR)\1_16k.res" \
	"$(OUTDIR)\2_16k.res" \
	"$(OUTDIR)\3_16k.res" \
	"$(OUTDIR)\4_16k.res" \
	"$(OUTDIR)\5_16k.res" \
	"$(OUTDIR)\6_16k.res" \
	"$(OUTDIR)\7_16k.res" \
	"$(OUTDIR)\8_16k.res" \
	"$(OUTDIR)\9_16k.res" \
	"$(OUTDIR)\10_16k.res" \
	"$(OUTDIR)\11_16k.res" \
	"$(OUTDIR)\12_16k.res" \
	"$(OUTDIR)\Dian_16k.res" \
	"$(OUTDIR)\DING_16k.res" \
	"$(OUTDIR)\Fen_16k.res" \
	"$(OUTDIR)\Liang_16k.res" \
	"$(OUTDIR)\LingChen_16k.res" \
	"$(OUTDIR)\Miao_16k.res" \
	"$(OUTDIR)\Nian_16k.res" \
	"$(OUTDIR)\Ri_16k.res" \
	"$(OUTDIR)\ShangWu_16k.res" \
	"$(OUTDIR)\WanShang_16k.res" \
	"$(OUTDIR)\XianZaiShiKe_16k.res" \
	"$(OUTDIR)\XiaWu_16k.res" \
	"$(OUTDIR)\Yue_16k.res" \
	"$(OUTDIR)\Zheng_16k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\isr.obj" \
	"$(OUTDIR)\Key.obj" \
	"$(OUTDIR)\Sound.obj" \
	"$(OUTDIR)\Clock.obj" \
	"$(OUTDIR)\Clock_Adjust.obj" \
	"$(OUTDIR)\Clock_Speech.obj" \
	"$(OUTDIR)\main.obj" 

"$(OUTDIR)\0_16k.res": "F:\myproject\lingyang\sound\Snd\0.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\0.16k" "$(OUTDIR)\0_16k.res" RES_0_16K 

"$(OUTDIR)\1_16k.res": "F:\myproject\lingyang\sound\Snd\1.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\1.16k" "$(OUTDIR)\1_16k.res" RES_1_16K 

"$(OUTDIR)\2_16k.res": "F:\myproject\lingyang\sound\Snd\2.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\2.16k" "$(OUTDIR)\2_16k.res" RES_2_16K 

"$(OUTDIR)\3_16k.res": "F:\myproject\lingyang\sound\Snd\3.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\3.16k" "$(OUTDIR)\3_16k.res" RES_3_16K 

"$(OUTDIR)\4_16k.res": "F:\myproject\lingyang\sound\Snd\4.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\4.16k" "$(OUTDIR)\4_16k.res" RES_4_16K 

"$(OUTDIR)\5_16k.res": "F:\myproject\lingyang\sound\Snd\5.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\5.16k" "$(OUTDIR)\5_16k.res" RES_5_16K 

"$(OUTDIR)\6_16k.res": "F:\myproject\lingyang\sound\Snd\6.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\6.16k" "$(OUTDIR)\6_16k.res" RES_6_16K 

"$(OUTDIR)\7_16k.res": "F:\myproject\lingyang\sound\Snd\7.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\7.16k" "$(OUTDIR)\7_16k.res" RES_7_16K 

"$(OUTDIR)\8_16k.res": "F:\myproject\lingyang\sound\Snd\8.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\8.16k" "$(OUTDIR)\8_16k.res" RES_8_16K 

"$(OUTDIR)\9_16k.res": "F:\myproject\lingyang\sound\Snd\9.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\9.16k" "$(OUTDIR)\9_16k.res" RES_9_16K 

"$(OUTDIR)\10_16k.res": "F:\myproject\lingyang\sound\Snd\10.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\10.16k" "$(OUTDIR)\10_16k.res" RES_10_16K 

"$(OUTDIR)\11_16k.res": "F:\myproject\lingyang\sound\Snd\11.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\11.16k" "$(OUTDIR)\11_16k.res" RES_11_16K 

"$(OUTDIR)\12_16k.res": "F:\myproject\lingyang\sound\Snd\12.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\12.16k" "$(OUTDIR)\12_16k.res" RES_12_16K 

"$(OUTDIR)\Dian_16k.res": "F:\myproject\lingyang\sound\Snd\Dian.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Dian.16k" "$(OUTDIR)\Dian_16k.res" RES_DIAN_16K 

"$(OUTDIR)\DING_16k.res": "F:\myproject\lingyang\sound\Snd\DING.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\DING.16k" "$(OUTDIR)\DING_16k.res" RES_DING_16K 

"$(OUTDIR)\Fen_16k.res": "F:\myproject\lingyang\sound\Snd\Fen.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Fen.16k" "$(OUTDIR)\Fen_16k.res" RES_FEN_16K 

"$(OUTDIR)\Liang_16k.res": "F:\myproject\lingyang\sound\Snd\Liang.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Liang.16k" "$(OUTDIR)\Liang_16k.res" RES_LIANG_16K 

"$(OUTDIR)\LingChen_16k.res": "F:\myproject\lingyang\sound\Snd\LingChen.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\LingChen.16k" "$(OUTDIR)\LingChen_16k.res" RES_LINGCHEN_16K 

"$(OUTDIR)\Miao_16k.res": "F:\myproject\lingyang\sound\Snd\Miao.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Miao.16k" "$(OUTDIR)\Miao_16k.res" RES_MIAO_16K 

"$(OUTDIR)\Nian_16k.res": "F:\myproject\lingyang\sound\Snd\Nian.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Nian.16k" "$(OUTDIR)\Nian_16k.res" RES_NIAN_16K 

"$(OUTDIR)\Ri_16k.res": "F:\myproject\lingyang\sound\Snd\Ri.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Ri.16k" "$(OUTDIR)\Ri_16k.res" RES_RI_16K 

"$(OUTDIR)\ShangWu_16k.res": "F:\myproject\lingyang\sound\Snd\ShangWu.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\ShangWu.16k" "$(OUTDIR)\ShangWu_16k.res" RES_SHANGWU_16K 

"$(OUTDIR)\WanShang_16k.res": "F:\myproject\lingyang\sound\Snd\WanShang.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\WanShang.16k" "$(OUTDIR)\WanShang_16k.res" RES_WANSHANG_16K 

"$(OUTDIR)\XianZaiShiKe_16k.res": "F:\myproject\lingyang\sound\Snd\XianZaiShiKe.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\XianZaiShiKe.16k" "$(OUTDIR)\XianZaiShiKe_16k.res" RES_XIANZAISHIKE_16K 

"$(OUTDIR)\XiaWu_16k.res": "F:\myproject\lingyang\sound\Snd\XiaWu.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\XiaWu.16k" "$(OUTDIR)\XiaWu_16k.res" RES_XIAWU_16K 

"$(OUTDIR)\Yue_16k.res": "F:\myproject\lingyang\sound\Snd\Yue.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Yue.16k" "$(OUTDIR)\Yue_16k.res" RES_YUE_16K 

"$(OUTDIR)\Zheng_16k.res": "F:\myproject\lingyang\sound\Snd\Zheng.16k"
	$(RESC) "F:\myproject\lingyang\sound\Snd\Zheng.16k" "$(OUTDIR)\Zheng_16k.res" RES_ZHENG_16K 

"$(OUTDIR)\Resource.obj": "F:\myproject\lingyang\sound\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "F:\myproject\lingyang\sound\Resource.asm" 

"$(OUTDIR)\hardware.obj": "F:\myproject\lingyang\sound\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "F:\myproject\lingyang\sound\hardware.asm" 

"$(OUTDIR)\isr.obj": "F:\myproject\lingyang\sound\isr.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\isr.lst" -o "$(OUTDIR)\isr.obj" "F:\myproject\lingyang\sound\isr.asm" 

"$(OUTDIR)\Key.obj": "F:\myproject\lingyang\sound\Key.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Key.lst" -o "$(OUTDIR)\Key.obj" "F:\myproject\lingyang\sound\Key.asm" 

"$(OUTDIR)\Sound.asm": "F:\myproject\lingyang\sound\Sound.c" ".\spce061a.h" ".\A2000.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/Sound.asm" "F:/myproject/lingyang/sound/Sound.c" 

"$(OUTDIR)\Sound.obj": "$(OUTDIR)\Sound.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Sound.lst" -o "$(OUTDIR)\Sound.obj" "$(OUTDIR)\Sound.asm" 

"$(OUTDIR)\Clock.asm": "F:\myproject\lingyang\sound\Clock.c" ".\spce061a.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/Clock.asm" "F:/myproject/lingyang/sound/Clock.c" 

"$(OUTDIR)\Clock.obj": "$(OUTDIR)\Clock.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Clock.lst" -o "$(OUTDIR)\Clock.obj" "$(OUTDIR)\Clock.asm" 

"$(OUTDIR)\Clock_Adjust.asm": "F:\myproject\lingyang\sound\Clock_Adjust.c" ".\spce061a.h" ".\Sound.h" ".\Clock.h" ".\Clock_Speech.h" ".\Key.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/Clock_Adjust.asm" "F:/myproject/lingyang/sound/Clock_Adjust.c" 

"$(OUTDIR)\Clock_Adjust.obj": "$(OUTDIR)\Clock_Adjust.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Clock_Adjust.lst" -o "$(OUTDIR)\Clock_Adjust.obj" "$(OUTDIR)\Clock_Adjust.asm" 

"$(OUTDIR)\Clock_Speech.asm": "F:\myproject\lingyang\sound\Clock_Speech.c" ".\Clock.h" ".\Sound.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/Clock_Speech.asm" "F:/myproject/lingyang/sound/Clock_Speech.c" 

"$(OUTDIR)\Clock_Speech.obj": "$(OUTDIR)\Clock_Speech.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Clock_Speech.lst" -o "$(OUTDIR)\Clock_Speech.obj" "$(OUTDIR)\Clock_Speech.asm" 

"$(OUTDIR)\main.asm": "F:\myproject\lingyang\sound\main.c" ".\spce061a.h" ".\Sound.h" ".\Key.h" ".\Clock.h" ".\Clock_Speech.h" ".\Clock_Adjust.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "F:/myproject/lingyang/sound/main.c" 

"$(OUTDIR)\main.obj": "$(OUTDIR)\main.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\0_16k.res" 
	$(RM) "$(OUTDIR)\1_16k.res" 
	$(RM) "$(OUTDIR)\2_16k.res" 
	$(RM) "$(OUTDIR)\3_16k.res" 
	$(RM) "$(OUTDIR)\4_16k.res" 
	$(RM) "$(OUTDIR)\5_16k.res" 
	$(RM) "$(OUTDIR)\6_16k.res" 
	$(RM) "$(OUTDIR)\7_16k.res" 
	$(RM) "$(OUTDIR)\8_16k.res" 
	$(RM) "$(OUTDIR)\9_16k.res" 
	$(RM) "$(OUTDIR)\10_16k.res" 
	$(RM) "$(OUTDIR)\11_16k.res" 
	$(RM) "$(OUTDIR)\12_16k.res" 
	$(RM) "$(OUTDIR)\Dian_16k.res" 
	$(RM) "$(OUTDIR)\DING_16k.res" 
	$(RM) "$(OUTDIR)\Fen_16k.res" 
	$(RM) "$(OUTDIR)\Liang_16k.res" 
	$(RM) "$(OUTDIR)\LingChen_16k.res" 
	$(RM) "$(OUTDIR)\Miao_16k.res" 
	$(RM) "$(OUTDIR)\Nian_16k.res" 
	$(RM) "$(OUTDIR)\Ri_16k.res" 
	$(RM) "$(OUTDIR)\ShangWu_16k.res" 
	$(RM) "$(OUTDIR)\WanShang_16k.res" 
	$(RM) "$(OUTDIR)\XianZaiShiKe_16k.res" 
	$(RM) "$(OUTDIR)\XiaWu_16k.res" 
	$(RM) "$(OUTDIR)\Yue_16k.res" 
	$(RM) "$(OUTDIR)\Zheng_16k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\isr.obj" 
	$(RM) "$(OUTDIR)\isr.lst" 
	$(RM) "$(OUTDIR)\Key.obj" 
	$(RM) "$(OUTDIR)\Key.lst" 
	$(RM) "$(OUTDIR)\Sound.obj" 
	$(RM) "$(OUTDIR)\Sound.lst" 
	$(RM) "$(OUTDIR)\Sound.asm" 
	$(RM) "$(OUTDIR)\Clock.obj" 
	$(RM) "$(OUTDIR)\Clock.lst" 
	$(RM) "$(OUTDIR)\Clock.asm" 
	$(RM) "$(OUTDIR)\Clock_Adjust.obj" 
	$(RM) "$(OUTDIR)\Clock_Adjust.lst" 
	$(RM) "$(OUTDIR)\Clock_Adjust.asm" 
	$(RM) "$(OUTDIR)\Clock_Speech.obj" 
	$(RM) "$(OUTDIR)\Clock_Speech.lst" 
	$(RM) "$(OUTDIR)\Clock_Speech.asm" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

