#ifdef ZNFAT_DEL_FILE
#define ZNFAT_OPEN_FILE
#define SEARCH_LAST_USABLE_CLUSTER
#define ZNFAT_UPDATE_FSINFO_LAST_CLU
#define ZNFAT_UPDATE_FSINFO_FREE_CLU
#define ZNFAT_GETNEXTCLUSTER
#define ZNFAT_MODIFY_FAT
#endif

#ifdef ZNFAT_OPEN_FILE 
#define ZNFAT_ENTER_DIR
#define ZNFAT_TOFILENAME
#define FILENAMEMATCH
#define ZNFAT_GETNEXTCLUSTER
#define STR2UP
#endif

#ifdef  ZNFAT_ENTER_DIR
#define COMPARE_DIR_NAME
#define ZNFAT_GETNEXTCLUSTER
#endif

#ifdef ZNFAT_READ_FILE
#define  ZNFAT_SEEK_FILE
#define ZNFAT_GETNEXTCLUSTER
#endif

#ifdef ZNFAT_READ_FILEX
#define  ZNFAT_SEEK_FILE
#define ZNFAT_GETNEXTCLUSTER
#endif

#ifdef ZNFAT_ADD_DAT
#define  ZNFAT_SEEK_FILE
#define ZNFAT_MODIFY_FAT
#define ZNFAT_FIND_FREE_CLUST
#endif

#ifdef ZNFAT_SEEK_FILE
#define ZNFAT_GETNEXTCLUSTER
#endif

#ifdef ZNFAT_CREATE_DIR
#define ZNFAT_ENTER_DIR
#define ZNFAT_CREATE_REC
#endif

#ifdef ZNFAT_CREATE_FILE
#define  ZNFAT_OPEN_FILE
#define  ZNFAT_CREATE_DIR
#define ZNFAT_CREATE_REC
#endif

#ifdef ZNFAT_XCOPY_FILE
#define  ZNFAT_CREATE_FILE
#define  ZNFAT_OPEN_FILE
#define  ZNFAT_ADD_DAT
#define  ZNFAT_READ_FILE
#endif

#ifdef ZNFAT_RENAME_FILE
#define  ZNFAT_OPEN_FILE
#endif

#ifdef ZNFAT_CREATE_REC
#define FILL_REC_INF
#define ZNFAT_FIND_FREE_CLUST
#define ZNFAT_MODIFY_FAT
#define ZNFAT_GETNEXTCLUSTER
#define ZNFAT_EMPTY_CLUSTER
#endif

#ifdef ZNFAT_FIND_FREE_CLUST
#define ZNFAT_UPDATE_FSINFO_FREE_CLU
#define ZNFAT_EMPTY_CLUSTER
#define ZNFAT_UPDATE_FSINFO_LAST_CLU
#endif

#ifdef ZNFAT_UPDATE_FSINFO_FREE_CLU
#define znFAT_GET_REMAIN_CAP
#endif



