#####################################################################
#																	 
#	Created by u'nSP IDE		12:34:43	12/20/10
#
#####################################################################




APPDIR	= D:\PROGRA~1\Sunplus\UNSPID~1.0

OUTDIR	= .\Debug

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"C:/Documents and Settings/Administrator/桌面/jiayin-sunpus"

BODY	= -body SPCE060A_061A -bfile "d:\Program Files\Sunplus\unSP IDE Common\Body\SPCE060A_061A.cpt"

BINFILE	= "$(OUTDIR)\ex3_S480_Auto.S37"

ARYFILE	= "$(OUTDIR)\ex3_S480_Auto.ary"

SBMFILE	= "$(OUTDIR)\ex3_S480_Auto.sbm"

OPT	= -S -gstabs -Wall -mglobal-var-iram

ASFLAGS	= -t2 -d

CASFLAGS	= -t2 

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	= 

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\0_48k.res" \
	"$(OUTDIR)\1_48k.res" \
	"$(OUTDIR)\2_48k.res" \
	"$(OUTDIR)\3_48k.res" \
	"$(OUTDIR)\4_48k.res" \
	"$(OUTDIR)\5_48k.res" \
	"$(OUTDIR)\6_48k.res" \
	"$(OUTDIR)\7_48k.res" \
	"$(OUTDIR)\8_48k.res" \
	"$(OUTDIR)\9_48k.res" \
	"$(OUTDIR)\10_48k.res" \
	"$(OUTDIR)\dian_72k.res" \
	"$(OUTDIR)\fen_72k.res" \
	"$(OUTDIR)\WD_48k.res" \
	"$(OUTDIR)\ssd_72k.res" \
	"$(OUTDIR)\GX_48k.res" \
	"$(OUTDIR)\TR_48k.res" \
	"$(OUTDIR)\RUH_48k.res" \
	"$(OUTDIR)\TQ_48k.res" \
	"$(OUTDIR)\XZ_48k.res" \
	"$(OUTDIR)\shoot1_48k.res" \
	"$(OUTDIR)\music2_72k.res" \
	"$(OUTDIR)\music1_72k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\isr.obj" \
	"$(OUTDIR)\main.obj" \
	"$(OUTDIR)\interrupt1.obj" \
	"$(OUTDIR)\klock.obj" 

"$(OUTDIR)\0_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\0.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\0.48k" "$(OUTDIR)\0_48k.res" RES_0_48K 

"$(OUTDIR)\1_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\1.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\1.48k" "$(OUTDIR)\1_48k.res" RES_1_48K 

"$(OUTDIR)\2_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\2.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\2.48k" "$(OUTDIR)\2_48k.res" RES_2_48K 

"$(OUTDIR)\3_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\3.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\3.48k" "$(OUTDIR)\3_48k.res" RES_3_48K 

"$(OUTDIR)\4_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\4.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\4.48k" "$(OUTDIR)\4_48k.res" RES_4_48K 

"$(OUTDIR)\5_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\5.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\5.48k" "$(OUTDIR)\5_48k.res" RES_5_48K 

"$(OUTDIR)\6_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\6.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\6.48k" "$(OUTDIR)\6_48k.res" RES_6_48K 

"$(OUTDIR)\7_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\7.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\7.48k" "$(OUTDIR)\7_48k.res" RES_7_48K 

"$(OUTDIR)\8_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\8.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\8.48k" "$(OUTDIR)\8_48k.res" RES_8_48K 

"$(OUTDIR)\9_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\9.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\9.48k" "$(OUTDIR)\9_48k.res" RES_9_48K 

"$(OUTDIR)\10_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\10.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\10.48k" "$(OUTDIR)\10_48k.res" RES_10_48K 

"$(OUTDIR)\dian_72k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\dian.72k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\dian.72k" "$(OUTDIR)\dian_72k.res" RES_DIAN_72K 

"$(OUTDIR)\fen_72k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\fen.72k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\fen.72k" "$(OUTDIR)\fen_72k.res" RES_FEN_72K 

"$(OUTDIR)\WD_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\WD.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\WD.48k" "$(OUTDIR)\WD_48k.res" RES_WD_48K 

"$(OUTDIR)\ssd_72k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\ssd.72k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\ssd.72k" "$(OUTDIR)\ssd_72k.res" RES_SSD_72K 

"$(OUTDIR)\GX_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\GX.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\GX.48k" "$(OUTDIR)\GX_48k.res" RES_GX_48K 

"$(OUTDIR)\TR_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\TR.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\TR.48k" "$(OUTDIR)\TR_48k.res" RES_TR_48K 

"$(OUTDIR)\RUH_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\RUH.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\RUH.48k" "$(OUTDIR)\RUH_48k.res" RES_RUH_48K 

"$(OUTDIR)\TQ_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\TQ.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\TQ.48k" "$(OUTDIR)\TQ_48k.res" RES_TQ_48K 

"$(OUTDIR)\XZ_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\XZ.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\XZ.48k" "$(OUTDIR)\XZ_48k.res" RES_XZ_48K 

"$(OUTDIR)\shoot1_48k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\shoot1.48k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\shoot1.48k" "$(OUTDIR)\shoot1_48k.res" RES_SHOOT1_48K 

"$(OUTDIR)\music2_72k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\music2.72k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\music2.72k" "$(OUTDIR)\music2_72k.res" RES_MUSIC2_72K 

"$(OUTDIR)\music1_72k.res": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\music1.72k"
	$(RESC) "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\voice\music1.72k" "$(OUTDIR)\music1_72k.res" RES_MUSIC1_72K 

"$(OUTDIR)\Resource.obj": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\Resource.asm" 

"$(OUTDIR)\hardware.obj": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\hardware.asm" 

"$(OUTDIR)\isr.obj": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\isr.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\isr.lst" -o "$(OUTDIR)\isr.obj" "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\isr.asm" 

"$(OUTDIR)\main.asm": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\main.c" ".\spce061a.h" ".\s480.h" ".\bobao.h" ".\keyscan.h" ".\display.h" ".\interrupt.h" ".\interrupt1.h" ".\AD.h" ".\clock.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "C:/Documents and Settings/Administrator/桌面/jiayin-sunpus/main.c" 

"$(OUTDIR)\main.obj": "$(OUTDIR)\main.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 

"$(OUTDIR)\interrupt1.asm": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\interrupt1.c" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/interrupt1.asm" "C:/Documents and Settings/Administrator/桌面/jiayin-sunpus/interrupt1.c" 

"$(OUTDIR)\interrupt1.obj": "$(OUTDIR)\interrupt1.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\interrupt1.lst" -o "$(OUTDIR)\interrupt1.obj" "$(OUTDIR)\interrupt1.asm" 

"$(OUTDIR)\klock.asm": "C:\Documents and Settings\Administrator\桌面\jiayin-sunpus\klock.c" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/klock.asm" "C:/Documents and Settings/Administrator/桌面/jiayin-sunpus/klock.c" 

"$(OUTDIR)\klock.obj": "$(OUTDIR)\klock.asm"
	$(AS) $(CASFLAGS) $(INCLUDES) -l "$(OUTDIR)\klock.lst" -o "$(OUTDIR)\klock.obj" "$(OUTDIR)\klock.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\0_48k.res" 
	$(RM) "$(OUTDIR)\1_48k.res" 
	$(RM) "$(OUTDIR)\2_48k.res" 
	$(RM) "$(OUTDIR)\3_48k.res" 
	$(RM) "$(OUTDIR)\4_48k.res" 
	$(RM) "$(OUTDIR)\5_48k.res" 
	$(RM) "$(OUTDIR)\6_48k.res" 
	$(RM) "$(OUTDIR)\7_48k.res" 
	$(RM) "$(OUTDIR)\8_48k.res" 
	$(RM) "$(OUTDIR)\9_48k.res" 
	$(RM) "$(OUTDIR)\10_48k.res" 
	$(RM) "$(OUTDIR)\dian_72k.res" 
	$(RM) "$(OUTDIR)\fen_72k.res" 
	$(RM) "$(OUTDIR)\WD_48k.res" 
	$(RM) "$(OUTDIR)\ssd_72k.res" 
	$(RM) "$(OUTDIR)\GX_48k.res" 
	$(RM) "$(OUTDIR)\TR_48k.res" 
	$(RM) "$(OUTDIR)\RUH_48k.res" 
	$(RM) "$(OUTDIR)\TQ_48k.res" 
	$(RM) "$(OUTDIR)\XZ_48k.res" 
	$(RM) "$(OUTDIR)\shoot1_48k.res" 
	$(RM) "$(OUTDIR)\music2_72k.res" 
	$(RM) "$(OUTDIR)\music1_72k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\isr.obj" 
	$(RM) "$(OUTDIR)\isr.lst" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) "$(OUTDIR)\interrupt1.obj" 
	$(RM) "$(OUTDIR)\interrupt1.lst" 
	$(RM) "$(OUTDIR)\interrupt1.asm" 
	$(RM) "$(OUTDIR)\klock.obj" 
	$(RM) "$(OUTDIR)\klock.lst" 
	$(RM) "$(OUTDIR)\klock.asm" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

